---
- name: Check etc/ansible.cfg
  hosts: localhost
  tasks:
    - name: print etc/ansible.cfg
      ansible.builtin.debug:
            msg: "{{lookup('ansible.builtin.file', '/etc/ansible/ansible.cfg') }}"
