---
- name: Check etc/ansible.cfg
  hosts: localhost
  tasks:
    - name: print etc/ansible.cfg
      ansible.builtin.debug:
            msg: "the value of foo.txt is {{lookup('ansible.builtin.file', '/etc/ansible.cfg') }}"
